server:
  address: localhost
  port: 8088
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

spring:
  main:
    banner-mode: off
  sql:
    init:
      mode: always
      encoding: UTF-8
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR